# Generated by Django 3.0.5 on 2020-06-03 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture_url', models.CharField(max_length=200, null=True)),
                ('user_id', models.IntegerField()),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
