# Generated by Django 2.0.1 on 2020-05-03 21:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blogpost', '0002_auto_20200503_2115'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogpostContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=10)),
                ('title_content', models.CharField(max_length=200)),
                ('body_content', models.TextField()),
                ('last_updated', models.DateField(auto_now=True)),
                ('blogpost_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blogpost', to='blogpost.Blogpost')),
            ],
        ),
    ]
