# Generated by Django 3.0.5 on 2020-05-21 21:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogpost', '0002_auto_20200521_2110'),
        ('blogpost_content', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpostcontent',
            name='blogpost',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blogpost', to='blogpost.Blogpost'),
        ),
    ]
