# Generated by Django 3.0.5 on 2020-05-26 05:52

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('blogpost_content', '0002_auto_20200521_2110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpostcontent',
            name='body_content',
            field=tinymce.models.HTMLField(),
        ),
    ]
