# Generated by Django 3.0.5 on 2020-05-30 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogpost_content', '0004_auto_20200530_2129'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpostcontent',
            name='created_at',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='blogpostcontent',
            name='is_draft',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='blogpostcontent',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
    ]
