# Generated by Django 3.0.5 on 2020-06-01 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogpost_content', '0005_auto_20200530_2143'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpostcontent',
            name='last_updated',
        ),
        migrations.AddField(
            model_name='blogpostcontent',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='blogpostcontent',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
