# Generated by Django 3.0.5 on 2020-06-02 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogpost_content', '0006_auto_20200601_0549'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpostcontent',
            name='is_published',
        ),
        migrations.AddField(
            model_name='blogpostcontent',
            name='publish_at',
            field=models.DateTimeField(null=True),
        ),
    ]
