# Generated by Django 3.0.5 on 2020-05-09 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blogpost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_url', models.CharField(max_length=200, null=True)),
                ('author_id', models.IntegerField()),
                ('posted_on', models.DateField()),
                ('last_updated', models.DateField(auto_now=True)),
            ],
        ),
    ]
