# Generated by Django 3.0.5 on 2020-06-01 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogpost', '0003_auto_20200530_2129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='slug',
            field=models.SlugField(max_length=255),
        ),
    ]
