# Generated by Django 3.0.5 on 2020-06-02 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogpost', '0004_auto_20200601_0541'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='category',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='last_updated',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='posted_on',
        ),
    ]
