# Generated by Django 3.0.5 on 2020-06-02 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogpost', '0005_auto_20200602_0437'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True,
                                        serialize=False,
                                        verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('blogpost', models.ManyToManyField(blank=True, to='blogpost.Blogpost')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
