# Generated by Django 3.0.5 on 2020-06-02 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogpost', '0006_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
