# Generated by Django 3.0.5 on 2020-05-15 03:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application_form', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationform',
            name='email',
            field=models.EmailField(default=None, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='applicationform',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default=None, max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='applicationform',
            name='location',
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='applicationform',
            name='nationality',
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='applicationform',
            name='phone',
            field=models.CharField(default=None, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
            preserve_default=False,
        ),
    ]
