# Generated by Django 3.0.5 on 2020-05-29 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application_form', '0002_auto_20200515_0312'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='applicationform',
            options={'ordering': ['-id']},
        ),
        migrations.RemoveField(
            model_name='applicationform',
            name='location',
        ),
        migrations.RemoveField(
            model_name='applicationform',
            name='nationality',
        ),
        migrations.AddField(
            model_name='applicationform',
            name='additional_input',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='applicationform',
            name='country_of_origin',
            field=models.CharField(default='USA', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='applicationform',
            name='destination_school',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='applicationform',
            name='goals',
            field=models.CharField(default='placeholder thing I want to gain', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='applicationform',
            name='grade_level',
            field=models.CharField(choices=[('high_school', 'High School'), ('undergraduate', 'Undergraduate'), ('exchange', 'Exchange Student'), ('transfer', 'Transfer Student'), ('graduate', 'Graduate Student')], default='graduate', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='applicationform',
            name='major',
            field=models.CharField(default='B.S. In Placeholder Studies', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='applicationform',
            name='preferred_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='applicationform',
            name='referral',
            field=models.CharField(default='Placeholder.com', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='applicationform',
            name='school_city',
            field=models.CharField(default='Placeholderville', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='applicationform',
            name='school_country',
            field=models.CharField(default='Placeholderia', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='applicationform',
            name='school_name',
            field=models.CharField(default='Placeholder Institute of Technology', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='applicationform',
            name='school_state',
            field=models.CharField(default='Placeholder Province', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='applicationform',
            name='topics_of_interest',
            field=models.CharField(default='Placeholder Interview Prep', max_length=300),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='applicationform',
            name='email',
            field=models.EmailField(max_length=100),
        ),
        migrations.AlterField(
            model_name='applicationform',
            name='first_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='applicationform',
            name='last_name',
            field=models.CharField(max_length=100),
        ),
    ]
