# Generated by Django 3.0.5 on 2020-05-30 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application_form', '0002_auto_20200515_0312'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='applicationform',
            options={'ordering': ['-id']},
        ),
    ]
