# Generated by Django 3.0.5 on 2020-05-29 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application_form', '0003_auto_20200529_0608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationform',
            name='topics_of_interest',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
