# Generated by Django 3.0.5 on 2020-05-29 07:22

from django.db import migrations, models
from datetime import datetime


class Migration(migrations.Migration):

    dependencies = [
        ('application_form', '0004_auto_20200529_0707'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationform',
            name='birth_date',
            field=models.DateTimeField(default=datetime.now(), max_length=100),
            preserve_default=False,
        ),
    ]
