# Generated by Django 3.0.5 on 2020-05-30 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='school',
            options={'ordering': ['-id']},
        ),
    ]
