# Generated by Django 2.0.1 on 2020-05-03 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogpost_content', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpostcontent',
            old_name='blogpost_id',
            new_name='blogpost',
        ),
    ]
